[package]
edition.workspace = true
license.workspace = true
name = "katana-pipeline"
repository.workspace = true
version.workspace = true

[dependencies]
katana-core.workspace = true
katana-executor.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-provider = { workspace = true, features = [ "test-utils" ] }
katana-rpc-types.workspace = true
katana-tasks.workspace = true

anyhow.workspace = true
async-trait.workspace = true
backon = { version = "1.3.0", features = [ "tokio-sleep" ] }
futures.workspace = true
parking_lot = "0.12.3"
serde_json = "1.0.133"
starknet.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
