[package]
edition.workspace = true
license.workspace = true
license-file.workspace = true
name = "katana-feeder-gateway"
repository.workspace = true
version.workspace = true

[dependencies]
katana-primitives.workspace = true
katana-rpc-types.workspace = true

reqwest.workspace = true
serde.workspace = true
serde_json = "1.0.133"
serde_json_path_to_error = "0.1.4"
starknet.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tokio.workspace = true
